spring:
  application:
    name: iara-api

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 2
      max-lifetime: 300000
      idle-timeout: 60000
      validation-timeout: 5000
      connection-timeout: 20000
      minimum-idle: 5

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      ssl:
        enabled: true
      timeout: 10000
      url: ${REDIS_URI}

springdoc:
  swagger-ui:
    path: /api-docs

logging:
  level:
    org:
      springframework:
        security: debug