name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Cache do Maven
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Compilar e testar
        run: mvn clean verify -B

      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build da imagem Docker
        run: |
          IMAGE_NAME=${{ secrets.DOCKER_USERNAME }}/iara-api-sql:latest
          echo "Construindo imagem: $IMAGE_NAME"
          docker build -t $IMAGE_NAME .

      - name: Push da imagem para o Docker Hub
        run: |
          IMAGE_NAME=${{ secrets.DOCKER_USERNAME }}/iara-api-sql:latest
          docker push $IMAGE_NAME

      - name: Deploy na Cloud
        if: success()
        run: |
          echo "Etapa de deploy (ex: Railway, Render, Fly.io, etc)"
