name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Cache do Maven
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Rodar testes
        run: mvn test

      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build e Push da imagem Docker
        run: |
          IMAGE_NAME=${{ secrets.DOCKER_USERNAME }}/iara-api-sql
          IMAGE_TAG=${{ github.sha }}
          echo "Construindo imagem Docker: $IMAGE_NAME:$IMAGE_TAG"
          docker build -t $IMAGE_NAME:$IMAGE_TAG -t $IMAGE_NAME:latest .
          echo "Enviando imagem para o Docker Hub..."
          docker push $IMAGE_NAME:$IMAGE_TAG
          docker push $IMAGE_NAME:latest

      - name: Deploy no Render
        if: success()
        run: |
          echo "Iniciando deploy no Render..."
          curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}

      - name: Notificação de sucesso
        if: success()
        run: echo "Deploy concluído com sucesso!"
